# Sample values for apigateway.
# This helm chart deploys a kubernetes deployment for an apigateway and a matching service.
# This is a YAML-formatted file.

replicaCount: 1

antiAffinity: "soft"
antiAffinityTopologyKey: "kubernetes.io/hostname"

image:
    # Use the url pointing to your repository.
    #repository: <yourDockerRegistry>:<RegistryPort>/<PathToApiGateway>
    #tag: <ImageTag>
    repository: ""
    tag: ""
        # The default pull policy is IfNotPresent which causes the Kubelet to skip pulling an image if it already exists.
        # If you would like to always force a pull use "Always"
    pullPolicy: IfNotPresent

# Secrets you need to pull image frome the repository
imagePullSecrets: []

service:
    type: LoadBalancer

# Port of Integration Server used in the Docker image. Default port is: 5555
is:
    port: 5555

# Port of ApiGateway used in the Docker image. Default port is: 9072
apigateway:
    port: 9072
    
# External Ports in case of Reverse Invoke configuration
# This will be needed only for the deployment in DMZ
externalPorts:
  enabled: false
  extPort: 
  extPortName: ""
  regPort:
  regPortName: ""

# Use only elasticsearch_external, elasticsearch_sidecar or elasticsearch_embedded,
# Depending on your environment and intentions.
# Replaced the sample data with the one that suits your environment.

#Datas to reach your external elasticsearch.
    # Url pointing to your running elasticsearch for example: 127.0.0.1:9200
    # Use true if your elasticsearch has https enabled, false if not.
    # Fill in your elasticsearch username for example: elastic
    # Fill in your elasticsearch password for example: changeme
elasticsearch_external: {}
#    host: "<UrlToYourExternalElasticsearch>:<elasticsearchPort>"
#    https: <"false" or "true">
#    username: <elasticsearchUsername>
#    password: <elasticsearchPassword>

# Docker image for elasticsearch. Default is: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
elasticsearch_sidecar: {}
#    image: docker.elastic.co/elasticsearch/elasticsearch
#    tag: 7.2.0

# Port of the embedded elasticsearch used inside off the container. Default is: 9240
elasticsearch_embedded: {}
#    port: 9240

# If a terracotta_host is set, the api gateway(s) will try to connect them to the terracotta host and cluster them.
# Please be aware that the terracotta license have to be available in die docker image of the apiGateway.
# This will only work with an external elasticsearch
# Terracotta_host: "terracottahost:9510"
terracotta_host: ""

terracotta_licenseKey:
#  terracotta_license.key |

licenseKey:
#  license.xml |

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}

nodeSelector: {}

tolerations: []
