{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "terracotta.serviceAccountName" . }}
  labels:
{{ include "terracotta.labels" . | nindent 4 }}
{{- end -}}
