---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "terracotta.uname" . }}-headless
  labels:
    app: "{{ include "terracotta.uname" . }}"
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  ports:
    - name: server
      port: {{ .Values.ports.serverPort }}
    - name: replication
      port: {{ .Values.ports.replicationPort }}
    - name: management
      port: {{ .Values.ports.managementPort }}
  selector:
    app: "{{ include "terracotta.uname" . }}"
